---
date: "June 17, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A Map of Historical Sites in Cairo, Egypt

```{r}
library(leaflet)

CairoLatLong <- data.frame(
  latitude=c(29.976480,30.047503,30.041833166, 30.024333236, 30.005461 ),
  longitude=c(31.131302,31.233702,31.257332304, 31.256832306, 31.230161)
)

content <- c(
    "<a href = 'http://egypt.travel/en/attractions/giza-plateau'> Giza-plateau </a>",
    "<a href = 'http://egypt.travel/attractions/the-egyptian-museum/'> Egyptian Museum </a> ",
    "<a href = 'http://egypt.travel/en/attractions/khan-el-khalili'> Khan-el-khalili </a>" ,
    "<a href = 'http://egypt.travel/en/attractions/salah-el-din-citadel-in-cairo'> Salah-el-din Citadel </a> ",
    "<a href = 'http://egypt.travel/en/attractions/the-hanging-church'> The Hanging Church </a>")


EgyptIcon <- makeIcon(
  iconUrl = "https://www.dailyscanner.com/wp-content/uploads/2019/10/Eye-of-Ra.png",
  iconWidth = 38, iconHeight = 95,
  iconAnchorX = 22, iconAnchorY = 94
)


CairoLatLong %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers(icon = EgyptIcon, popup = content)


```

